server:
   port: 9100
   
   
   
spring:
  cloud:
    gateway:
      routes:
        #Route Mapping
      - id: cropDetails              #RouteIdentifier
        uri: http://localhost:9000/         #Respective microservice URL which needs to be mapped
         #Request Context Path Mapping
        predicates:
        - Path=/api/crops/**          

 
        #Route Mapping - With out Filters 
      - id: order-service
        uri: http://localhost:9300/
        predicates:
        - Path=/api/dealer/**
        
        
 
  application:
        name: crop-api-gateway